//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PROYECTO_UNIDAD_III
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empresa
    {
        public string Nombre { get; set; }
        public string Mision { get; set; }
        public string VIsion { get; set; }
        public string Nosotros { get; set; }
        public int ID { get; set; }
    }
}
