//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PROYECTO_UNIDAD_III
{
    using System;
    using System.Collections.Generic;
    
    public partial class Portafolio
    {
        public int id { get; set; }
        public string NombreProducto { get; set; }
        public string Detalles { get; set; }
        public Nullable<double> Precio { get; set; }
        public byte[] Foto { get; set; }
    }
}
